### ISSUE TITLE
launching on ipad

### ISSUE THREAD

**Issue by jasonshark** [appcelerator/appc-install#31]
I ran `$ appc run` and my project launched in the iPhone simulator. Woohoo!

What command can I use to launch my app in the iPad simulator?

**Comment by jhaynie** [comment]
try running:

`appc ti help build`

to give you help on different launch options during run.

we should move this conversion over to https://community.appcelerator.com for any followup, thanks.

hope that helps!

**Comment by jasonshark** [comment]
Thanks! :+1:
